### ISSUE TITLE
Add support for custom headers

### ISSUE THREAD

**Issue by Ohadbasan** [ironSource/atom-go#2]
We need to add support for custom http headers for each byte array being sent to the batcher.

**Comment by a8m** [comment]
You can implement your own [poster](https://github.com/ironSource/atom-go/blob/master/client.go#L21)(minimal http client) and pass it as a config option.
for example:
```go
svc := atom.New(&atom.Config{
    ApiKey: "YOUR_API_KEY",
    // your poster implementation
    Client: poster,
})
```
